controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Controladores de posici贸n para los ejes boogie
    eje_boogie_position_controller:
      type: position_controllers/JointGroupPositionController

    # Controladores de posici贸n para ang_izq y ang_der
    ang_position_controller:
      type: position_controllers/JointGroupPositionController

    # Controladores de velocidad para vel_izq y vel_der
    vel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Controladores de velocidad para LIDAR
    lidar_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


# Controladores de posici贸n para los ejes boogie
eje_boogie_position_controller:
  ros__parameters:
    joints:
      - eje_boogie_1
      - eje_boogie_2
      - eje_boogie_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    gains:
      eje_boogie_1: {p: 10.0, i: 1.0, d: 5.0, feedforward_gain: 1.0, antiwindup: true, i_clamp_max: 5.0, i_clamp_min: -5.0}
      eje_boogie_2: {p: 10.0, i: 1.0, d: 5.0, feedforward_gain: 1.0, antiwindup: true, i_clamp_max: 5.0, i_clamp_min: -5.0}
      eje_boogie_3: {p: 10.0, i: 1.0, d: 5.0, feedforward_gain: 1.0, antiwindup: true, i_clamp_max: 5.0, i_clamp_min: -5.0}


# Controladores de posici贸n para ang_izq y ang_der
ang_position_controller:
  ros__parameters:
    joints:
      - ang_izq_1
      - ang_izq_2
      - ang_izq_3
      - ang_der_1
      - ang_der_2
      - ang_der_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort

# Controladores de velocidad para vel_izq y vel_der
vel_velocity_controller:
  ros__parameters:
    joints:
      - vel_izq_1
      - vel_izq_2
      - vel_izq_3
      - vel_der_1
      - vel_der_2
      - vel_der_3
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort

# Controladores de velocidad para LIDAR
lidar_velocity_controller:
  ros__parameters:
    joints:
      - lidar
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort